name: ci
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  composer-outdated:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
      - name: Install packages
        run: composer install
      - name: Check dependencies for available updates
        run: composer outdated --ansi -D -m --strict

  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
      - name: Install packages
        run: |
          composer install
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: "./vendor/bin/pest"